config/routes.rb
Rails.application.routes.draw do
  get 'home/login'

  resources :comments

  resources :posts
  get 'posts/enable/:id' => 'posts#enable'
  get 'posts/disable/:id' => 'posts#disable'

  root 'home#login'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user

  has_attached_file :media
  do_not_validate_attachment_file_type :media

  def enabled?
    self.post_enabled
  end

  def enable
    self.post_enabled = true
  end

  def disable
    self.post_enabled = false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = session[:user_id] # author

    @comment.save
    redirect_to :back

    #respond_to do |format|
      #if @comment.save
        #format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        #format.json { render :show, status: :created, location: @comment }
      #else
        #format.html { render :new }
        #format.json { render json: @comment.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :post_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def login
    # get client ip
    ip = request.remote_ip
    
    # save new ip
    user = User.find_by_ip(ip) || User.new(ip: ip)
    user.save # save user data

    # store ip in session
    session[:user_id] = user.id

    # redirect to posts index
    redirect_to posts_url
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :enable, :disable]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id] # author
    @post.prev_post_id = nil # previous post
    @post.next_post_id = nil # next post

    respond_to do |format|
      #setting author
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /posts/enable/1
  def enable
    @post.enable
    @post.save

    redirect_to posts_url
  end

  # GET /posts/disable/1
  def disable
    @post.disable
    @post.save

    redirect_to posts_url
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :media)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_number_of_machine
    # machine number = last ip address number + 1
    User.find(session[:user_id]).ip.split('.')[3].to_i
  end

  def get_ip_of_machine
    User.find(session[:user_id]).ip
  end

  def is_admin?
    # TODO move this to config file
    admin_ip = [
      #'127.0.0.1',
      '192.168.1.230',
      #'192.168.1.110',
    ]

    true if admin_ip.include? get_ip_of_machine
  end

  def server_ip
    '192.168.1.230'
  end

  def server_port
    '3000'
  end

  def generate_direct_link link
    "http://#{server_ip}:#{server_port}#{link}"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user.ip %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/login.html.erb
<h1>Home#login</h1>
<p>Find me in app/views/home/login.html.erb</p>

<p><%= request.remote_ip %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classvote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<center>
  <% if is_admin? %>
  <h1>管理员驾到!!</h1>
  <% end %>
  <h2><%= "#{get_number_of_machine}号机器，欢迎你登录！  你的IP地址是：#{get_ip_of_machine}" %> <%= link_to '回到首页', root_url %></h2>

<%= yield %>

</center>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :media %><br>
    <%= f.file_field :media %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<% @posts.each do |post| %>
  <% next if post.post_enabled == false && (not is_admin?) %>
  <h1><%= link_to post.title, post %></h1>
  <div>
  <% if is_admin? %>
    <% if post.post_enabled %><%= link_to 'disable', action: 'disable', id: post.id %><% end %>
    <% if not post.post_enabled %><%= link_to 'enable', action: 'enable', id: post.id %><% end %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  </div>
<% end %>

<br>
<% if is_admin? %>
  <%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @post.title %>
</h1>

<div>
  <%= @post.content %>
</div>

<div>
  <h2><a href="<%= generate_direct_link @post.media.url %>" target="_blank">播放Flash动画</a></h2>
</div>

<div>
  <h2>评论留言:</h2>
<% comment = Comment.new %>
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.text_area :content, style: "width:600px; height:100px;" %>
  </div>
  <div class="actions">
    <%= f.submit '发表评论' %>
  </div>
<% end %>
</div>

<div>
  <h2>同学们的评论:</h2>
  <table>
  </tbody>
  <% @post.comments.each do |comment| %>
    <tr>
    <td>
    <%= comment.user.ip %>
    在
    <%= comment.created_at.strftime('%Y-%m-%d %H:%M:%S').to_s %>
    说：
    </td>
    <td>
    <%= comment.content %>
    </td>
    <% if is_admin? %>
    <td>
        <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
    <% end %>
    </tr>
  <% end %>
  </tbody>
  </table>
</div>

<% if is_admin? %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<% end %>